name: deploy pages
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build:
    # Job name is Greeting
    name: Deploy page
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          ./deploy.sh
        uses: setup
